### ISSUE TITLE
Self.GET with typecasting

### ISSUE THREAD

**Issue by warpech** [Starcounter/Guidelines#11]
Which of the following ways to do a Self.GET is preferable and why?

```c#
var master = Self.GET<MasterPage>("/Products/master");
var master = (MasterPage)Self.GET("/Products/master");
```

I find the first one more *readable*, but I assume the second one is more *understandable* for a newbie.

Is there any performance difference?

**Comment by warpech** [comment]
@joozek78, @chrhol, @Mackiovello any suggestions here?

**Comment by Mackiovello** [comment]
I personally feel like the first one is better. The second one makes it look like it's an ad-hoc solution.

**Comment by joozek78** [comment]
Definitely first one. IMO we shouldn't account for someone who doesn't understand what happens here, otherwise we'll fall into a trap of triviality

**Comment by warpech** [comment]
Great, then we all agree!

@Mackiovello could you please fix instances of `(....)Self.GET` in the docs? For example here: https://github.com/Starcounter/Docs/blob/c910401342040488c9f12132d1989a1af4ce6c10/cookbook/attach-a-request-to-long-running-transactions/README.md

Should we add that to the Guidelines?

**Comment by Mackiovello** [comment]
It's now updated in the documentation

> Should we add that to the Guidelines?

It should probably be given a line in [C# code formatting](https://starcounter.gitbooks.io/guidelines/content/coding_style/csharp_code_formatting.html). If there are no objections, I'll go ahead and do that

**Comment by warpech** [comment]
I think that it deserves a new page in Guidelines: "Starcounter API notes"

**Comment by Mackiovello** [comment]
> I think that it deserves a new page in Guidelines: "Starcounter API notes"

Is there more content that should be on that page as well?

**Comment by joozek78** [comment]
I think it will filled gradually as we find more gotchas like this

**Comment by Mackiovello** [comment]
> I think it will filled gradually as we find more gotchas like this

Well, perhaps we might. The thing is that no one will read that page. Especially if it will contain things like this which are entirely cosmetic.

**Comment by joozek78** [comment]
Personally, I wouldn't even write that down. It should be obvious for any
C# user which method should be used

**Comment by Mackiovello** [comment]
> Personally, I wouldn't even write that down. It should be obvious for any
C# user which method should be used

Then I would say that we should close this issue. The method that we agreed on can be used in the documentation for clarity, other than that, we can leave it be.

**Comment by warpech** [comment]
> It should be obvious for any C# user which method should be used

If it was obvious then we would not have half of our samples using `(MasterPage)Self.GET("/Products/master")`

**Comment by warpech** [comment]
The guideline was added at a new page: https://github.com/Starcounter/Guidelines/blob/master/starcounter-api-usage.md

If someone would like to propose a change or enhance the page, please make a PR.
