### ISSUE TITLE
Properties bound to actions ("Save$" vs "SaveClick$" vs "SaveTrigger$")

### ISSUE THREAD

**Issue by warpech** [Starcounter/Guidelines#12]
Continued from https://github.com/StarcounterSamples/KitchenSink/pull/91#issuecomment-281371211

We should have a convention how to call properties bound to actions in our JSON. Most of places have properties in JSON like:

```
{
   "Save$": 0
}
```

but sometimes it is:

```
{
   "SaveClick$": 0
}
```

I think that the "Click" suffix is redundant, because it only applies to the client. The server view-model does not care how is "Save" triggered. Is this click, or mouse up, or keyboard press? The server doesn't care, hence the event type should not be hardcoded in the name of the property.

**Comment by warpech** [comment]
Who votes for `Save$`

**Comment by warpech** [comment]
Who votes for `SaveClick$` 👍

**Comment by warpech** [comment]
@Mackiovello, @ubbeK, @alshakero, @andwah, @joozek78, @aloscha, @un-tone, @tomalec, @MMNosek, @diliger, @Loudness, @threezool, @joltrix - we need your votes

**Comment by alshakero** [comment]
I agree and vote for `Save$`. But I wish there was some suffix that reveals that this property is a triggering point. I can't tell any difference between `Save$` and `FirstName$`. Something like `$SaveVerb$` would be cool. 

Remember, I already voted, so I'm not hindering any progress, just sharing thoughts.

**Comment by warpech** [comment]
Interesting point! I just dislike calling the verb `Click`, because the server has never heard of clicking. Maybe `SaveAction$` or `SaveTrigger$`?

I keep my personal vote to `Save$` though, because I value concise code more.

**Comment by warpech** [comment]
Who votes for `SaveAction$` 👍

**Comment by warpech** [comment]
Who votes for `SaveTrigger$` 👍

**Comment by mmnosek** [comment]
:+1 for Save$

**Comment by Joltrix** [comment]
Hmm, I can't decide if

```
public void Handle(Input.SaveAction Action)
{
}
```
looks really nice, or way to repetetive..

perhaps a simple `Save$` `(Input.Save Action)` would look better

**Comment by andwah** [comment]
I voted for `SaveClick$` .

Just by locking at the Json you will quicker understand how things work.

**Comment by Mackiovello** [comment]
`SaveTrigger$` makes the most sense in all the different places:

Incrementing a trigger makes sense:
```html
<button value={{model.SaveTrigger$::click}} onclick="++this.value">Save</button>
```

Having a trigger as an int makes sense:
```json
{
  "SaveTrigger$": 0
}
```

Tracking an action of a trigger makes sense:
```cs
public void Handle(Input.SaveTrigger action)
```

**Comment by tomalec** [comment]
I totally agree with @Mackiovello, vote for `SaveTrigger$`

**Comment by threezool** [comment]
Were leaning toward `SaveAction$` but after the post from @Mackiovello i agree that `SaveTrigger$` make more sense.

**Comment by joozek78** [comment]
Can we close the polls and publish the guideline? It seems that `SaveTrigger$` won

**Comment by miyconst** [comment]
@warpech is to close the issue, @Mackiovello is to update the docs.

**Comment by warpech** [comment]
Thanks for bumping. I like `SaveTrigger$` too.

I will add `SaveTrigger$` to Guidelines and then ask @Mackiovello in a separate issue to update the Docs.

Regarding updating all of our sample apps... Yeah, this is something that takes time. I really wish everyone update the sample apps when they have a chance. I will create an issue in most popular apps.

**Comment by warpech** [comment]
Follow up issues created, thanks everyone!
