### ISSUE TITLE
Namespaces

### ISSUE THREAD

**Issue by warpech** [Starcounter/Guidelines#14]
In all our sample apps we have a convention that all classes are in a namespace `AppName`, so just `SignIn` (not `SignIn.ViewModels`), even when they are in subdirectory `ViewModels`.

What do you think about that? Should we change the convention?

**Comment by Mackiovello** [comment]
@threezool we've already messed up on this one 😄 

I personally like this because it easily becomes a namespace mess otherwise. Since the apps should be relatively small it shouldn't be an issue with a lack of namespace either.

**Comment by joozek78** [comment]
We should definitely change that!
To be honest, I never even thought about it as a convention, more like a mistake copied all over. Does anyone know any advantage to using app name as a namespace?

CC @Starcounter/apps

**Comment by joozek78** [comment]
@Mackiovello I can't agree with you. What you're saying is essentially that not using namespaces is cool if your code is small - and code tends to rapidly increase in size and complexity.
Using namespaces costs nothing and offers improved organization

**Comment by Mackiovello** [comment]
> @Mackiovello I can't agree with you. What you're saying is essentially that not using namespaces is cool if your code is small - and code tends to rapidly increase in size and complexity.
Using namespaces costs nothing and offers improved organization

Okay, that's a fair point. I'm conceding that I was a little naïve.

**Comment by warpech** [comment]
I believe that it was proposed originally by @Starcounter-Jack. @chrhol maybe you know some rationale for it? 

I believe that @Starcounter-Jack would actually love to see all the files in the project root, and have the app as small as possible. But with 10+ different screens that's not going to happen.

> Does anyone know any advantage to using app name as a namespace?

1. You can move the files between directories without changing their content.

**Comment by joozek78** [comment]
> Does anyone know any advantage to using app name as a namespace?
> You can move the files between directories without changing their content.

We usually keep all the viewmodels in one directory, anyway

**Comment by chrhol** [comment]
>  @chrhol maybe you know some rationale for it?

> I believe that @Starcounter-Jack would actually love to see all the files in the project root, and have the app as small as possible. But with 10+ different screens that's not going to happen.

Nothing more than what you already stated. I would guess that for a minimal sample it's good to remove all non-essential stuff to focus on the important parts and to get an easy overview. But when moving away from that, I think a correct structure is more important than worry about a few extra lines of code. 

Me personally, I really like when the namespaces follows the structure of the folders, makes it much more easy to find and maintain the code. But we have a lot of code internally in Level1 as well that doesn't follow this (an example is Starcounter.XSON where almost everything you use is declared in namespace `Starcounter`)

**Comment by mmnosek** [comment]
> Me personally, I really like when the namespaces follows the structure of the folders, makes it much more easy to find and maintain the code

I agree. I have a very good example in SWO project. We started with a small app (without namespaces following folders), but then project started to be bigger and bigger and without that, we have a little bit mess... 

> You can move the files between directories without changing their content.

Usually, we use VS + R# so moving is not a problem at all. A namespace is changed everywhere automatically.

So to sum up I think that following folder structure is a good idea 👍

**Comment by joozek78** [comment]
Can we just agree that not using namespaces is *not* our convention? I mean, using namespaces is as standard thing in C# as using variables, I don't think we have to emphasize the fact that we use them. I'd just close that issue

**Comment by warpech** [comment]
> **convention** - a way in which something is usually done, especially within a particular area or activity.

Right now we do have shallow namespaces in all of our sample apps, so I think that **yes**, it is a convention and we have to explicitly commit to changing that.

But it seems that we are unanimously agreeing with changing it. I have added it to the page https://starcounter.gitbooks.io/guidelines/content/coding_style/csharp_code_formatting.html (point 20)
