### ISSUE TITLE
Remove the "viewmodels"-folder in the wwwroot

### ISSUE THREAD

**Issue by threezool** [Starcounter/Guidelines#16]
After going thru the project structure guidelines i find it really confusing by having another folder in the wwwroot called "viewmodels" since it breaks two different programming conventions.

![image](https://cloud.githubusercontent.com/assets/7039347/24189608/f8070424-0ee5-11e7-9f3e-e6382f4d1d2c.png)

Following the convention of a web project, the html files are located in the root of a specific folder it is attached to. Index.html is in the wwwroot for example and then the rest of the pages are placed in relevant subfolders.

Then the MVVM convention says that the ViewModel is the data being prepared and then presented to a view, in this case the html file. The html file is a view that gets populated by the ViewModel data and resides in its own layer (in this case the wwwroot). To have the view placed inside another folder called viewmodel is just odd due to it not being a ViewModel and should more follow the folder structure of a web project as mentioned above.

So to follow conventions already set we should remove this folder and let the html views be placed in the root of "StarcounterExample" instead.

**Comment by joozek78** [comment]
I think that placing html files in the root (wwwroot/StarctounterSample)
would introduce unnecessary disorder. Currently all the categories have
their respective subdirectories. Why should one category be special? That
we'll say "root directory contains a subdirectory for each category plus
all the viewmodel html files" - it's inconsistent.
I think that current state of affairs is a clean, readable solution - I
don't see how anyone could be confused by it (and avoiding confusion is the
purpose of conventions, isn't it?)

That said, I see that what we actually put inside "viewmodels" subdirectory
are views (viewmodels are the csharp objects). I think we could consider
renaming the subdirectory to "views".

**Comment by warpech** [comment]
Thank you @threezool for reporting this. I think that for a small project it does not make sense to have `ViewModels` directories either in C# nor in HTML. But in larger projects the folder structure should be in both places, just for consistency.

On the other hand I agree that `viewmodels` is an unfortunate name. I agree that `views` is better.

@Starcounter/sc-apps anyone has some additional opinion?

**Comment by joozek78** [comment]
> I think that for a small project it does not make sense to have ViewModels directories either in C# nor in HTML

What do you mean? Creating directories cost nothing and has huge benefits later, when the project grows

**Comment by warpech** [comment]
Some projects are small and stay small. Do you think we should add subdirs to https://github.com/StarcounterApps/HelloWorld?

**Comment by joozek78** [comment]
I think that this project is not a real project ;) It's purpose is to show
in a minimal way how a basic app could be done. Not using namespaces would
be like using "var1" as variable name - in theory it saves you a bit time,
but you'll regret it in the future. "var1" could be (I'm not saying that's
the best idea) used as a name to illustrate how variables work, though.

**Comment by miyconst** [comment]
>@Starcounter/sc-apps anyone has some additional opinion?

I agree with what you say.

**Comment by ubbeK** [comment]
> On the other hand I agree that wwwroot/viewmodels is an unfortunate name. It should be changed to wwwroot/views.
> 
> @Starcounter/sc-apps anyone has some additional opinion?

I agree, `wwwroot/view` might be better, but as long as we follow our own coding style and don't waste time updating it in all repositories several times a year, I am fine with it.

**Comment by threezool** [comment]
I'm happy with calling it View instead, at least then it's clear what the folder actually contains. =)

**Comment by warpech** [comment]
Then decided, renaming that to `wwwroot/views` (plural, which also happens to be ASP.NET Core pattern): https://github.com/Starcounter/Guidelines/blob/master/project_structure.md

> I agree, `wwwroot/view` might be better, but as long as we follow our own coding style and don't waste time updating it in all repositories several times a year, I am fine with it.

I am sorry but most people follow our convention by copying what we have in the sample app repos. Therefore we need to be updating the structure in our sample app repos. 

Production projects of course can keep using whatever they have.

**Comment by warpech** [comment]
Closing as done. Updating the current projects can be done with other changes in them
