### ISSUE TITLE
Add CSS code formatting page

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Guidelines#2]

**Comment by warpech** [comment]
@miyconst what are the guidelines that you wanted to add? Maybe @Mackiovello can put it to words?

**Comment by warpech** [comment]
What I would like to see that:

- we are using BEM convention, with a link to our BEM page in the Docs
- how many CSS files should be in the project
- use only lowercase in CSS stylesheets

**Comment by warpech** [comment]
@tomalec can you pls help out here? Do we have formatting suggestions for CSS? Proposed `.editorconfig`?

**Comment by warpech** [comment]
Ping @tomalec, @miyconst. What is the formatting suggestion that you would like to use? I am asking because personally I don't give a damn, but I would like to have a recommendation for the new team members.

**Comment by tomalec** [comment]
I'd only add one point to the guidelines:
 - prefix Light DOM and shared Shadow DOM (layout compositions) classes and ids with your appname

Other than that I don't have any `.editorconfig` specified, but it would be good to have one.

**Comment by warpech** [comment]
Any opinion regarding the indentation? Visual Studio uses 4 spaces by default.

Example:

```cs
body {
    color: red;
}
```

I would keep it like that.

**Comment by warpech** [comment]
Implemented in https://github.com/Starcounter/Guidelines/pull/42

**Comment by warpech** [comment]
Closing as done
