### ISSUE TITLE
Branches in the apps

### ISSUE THREAD

**Issue by warpech** [Starcounter/Guidelines#20]
There is a proposal to change the branch names in sample apps.

Right now we have branches:

- `master`:
   - According to [branching.md](https://github.com/Starcounter/Guidelines/blob/master/branching.md): the branch that works with the latest Starcounter release version (2.2)
   - According to [continuous_integration.md](https://github.com/Starcounter/Guidelines/blob/master/continuous_integration.md) What is tested automatically: KitchenSink Master branch with Starcounter Release nightly (2.2)
- `develop`:
   - According to [branching.md](https://github.com/Starcounter/Guidelines/blob/master/branching.md): the branch that works with the latest Starcounter develop version and preferably also with the latest Starcounter release version (2.4, 2.2)
   - According to [continuous_integration.md](https://github.com/Starcounter/Guidelines/blob/master/continuous_integration.md) What is tested automatically: KitchenSink Develop branch with Starcounter RC nightly (2.3)

----

So it is a mess, because we have 3 release channels in Starcounter (develop, RC and release), 3 branches in Starcounter (develop, v2.2 and v2.3) and 2 branches in the apps. 

We propose to remove the branch `master` in the apps and switch to having the following branches:

- `develop` (for sc 2.4)
- `sc2.3`
- `sc2.2`

The **default** branch will be the same as what is currently pinned to the download button at Starcounter.io.

The PRs should be made to the `develop` branch.

@Starcounter/sc-apps WDYT?

**Comment by joozek78** [comment]
Why would we name one of the branch develop? Why not just 2.4. Other than
that I agree

**Comment by warpech** [comment]
> Why would we name one of the branch develop? Why not just 2.4. Other than
that I agree

I get your point. Here are my reasons:

1. Because Starcounter has a `develop` branch, not `v2.4` branch
2. To mark that that branch is the one from which the development should be made, unless you are doing a hot fix.

Do you think both don't matter that much?

**Comment by andwah** [comment]
Just curious why we want to call our `master `branch for `develop `and not `master `as it is in many other repos in github

**Comment by warpech** [comment]
> Just curious why we want to call our `master `branch for `develop `and not `master `as it is in many other repos in github

I want to rename `master` branch to `v2.3` and `v2.2` and keep `develop` as `develop`.

Most repos in GitHub have just one `master` branch because they have one target platform.

Some repos in GH have `master` and `develop` to distinct from stable and unstable code.

We want to distinct both stable/unstable code as well as the target platform version.

**Comment by andwah** [comment]
@warpech thanks for the explanation.

**Comment by joozek78** [comment]
But I thought the idea is to bind the branch names to specific version! If
we leave "develop" its meaning will change. Now it would be compatible with
2.4, but some time later it would be 2.5.
Second argument is the ease of choice. User can easily check which version
of starcounter he's using, but not which channel he used.

**Comment by warpech** [comment]
> Now it would be compatible with 2.4, but some time later it would be 2.5.

At a point when Level1 sprouts the branch `v2.4` from `develop` we will do the same in our sample apps.

**Comment by warpech** [comment]
Closing as there was no decision to do this.
