### ISSUE TITLE
Change build.bat to detect msbuild from VS Build Tools

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Guidelines#21]
1. download [VS build tools](https://www.visualstudio.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=15)
1. download People
1. build with `msbuild` from Build Tools directly (find it in Program Files, I can't remember exact path now) - no problem
1. `build.bat` tells me that I don't have Visual Studio installed - that's true, but it should support Build Tools

**Comment by warpech** [comment]
cc @KmaTTi89 

We thought we have that covered with `CALL "%programfiles(x86)%\Microsoft Visual Studio\2017\BuildTools\Common7\Tools\VsDevCmd.bat"` in https://github.com/Starcounter/Guidelines/blob/master/batch-files.md

Is the path wrong?

**Comment by joozek78** [comment]
This looks like it should work, but I recently checked this and it didn't work :| I'll check again

**Comment by joozek78** [comment]
It turns out that it's just People that does not use the latest build.bat version. Guidelines are okay
