### ISSUE TITLE
Deprecate QueryResultRows<T>.First

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Guidelines#22]
We have a property [QueryResultRows<T>.First](https://github.com/Starcounter/level1/blob/2d6990034e47906453c8108c6191bdf43aa78959/src/Starcounter/Query/SQL/SqlResultGeneric.cs#L126). It behaves just like LINQ's `.FirstOrDefault()` with two exceptions:

1. It has some kind of profiling code, I don't really know what is its purpose
1. It sets a "first only" flag, probably optimizing the query a little. That actually can be achieved by adding "FETCH 1" to the SQL query

Its main disadvantage is that it's confusing for any .NET user, because it's similar to `.First()`, but behaves differently - it will return null if there are no results, where `.First()` would throw an exception.

@Starcounter/sc-apps  Does anyone know a good reason not to deprecate it?

**Comment by warpech** [comment]
Actually there was a discussion about that: https://github.com/Starcounter/TechComm/issues/187

Can you pls update that thread with your current thoughts about it?

**Comment by Mackiovello** [comment]
Is there anything stopping me from changing all uses of `.First` in the documentation with `.FirstOrDefault()`?

**Comment by mtornwall** [comment]
> Is there anything stopping me from changing all uses of .First in the documentation with .FirstOrDefault()?

The default project template generates a C# file that doesn't import the `System.Linq` namespace. And what's worse, Intellisense may not be able to help by suggesting that the namespace be imported as `FirstOrDefault()` and friends are extension methods.

**Comment by Mackiovello** [comment]
> Thus, if it wasn't clear, new users' code could fail to compile with this change.

That sounds like a lot of fun! 

I'll not make any changes now before a real decision has been made then

**Comment by joozek78** [comment]
So how about we change the default template to include it? Or include the usings in our examples? Or just assume our users are thinking people able to add an import to LINQ?

Since no one spoke against the deprecation can go forward with this?

**Comment by Mackiovello** [comment]
> Or just assume our users are able to add an import to LINQ?

I think we can make that assumption. IntelliSense is able to detect that it's LINQ,  so I wouldn't worry too much.

**Comment by Mackiovello** [comment]
Closing in favor of https://github.com/Starcounter/level1/issues/4244
