### ISSUE TITLE
Common way to create MasterPage and Session

### ISSUE THREAD

**Issue by warpech** [Starcounter/Guidelines#23]
Many apps have different ways to create a MasterPage and attach a Session to it. Any thoughts about it?

I would like to propose the following:

1. Stop using `Self.GET` to get master page. This is a hack that's difficult to explain. It will be easier to grasp the reason for `Self.GET` if we use it **only** as a blending point.
2. Instead of `Handle.GET("/<appname>/master")` or `Handle.GET("/<appname>/standalone")` let's use a method like the below:

```cs
       protected MasterPage GetMasterFromSession()
        {
            if (Session.Current == null)
            {
                Session.Current = new Session(SessionOptions.PatchVersioning);
            }

            var master = Session.Current.Data as MasterPage;

            if (master == null)
            {
                master = new MasterPage();
                Session.Current.Data = master;
            }

            return master;
        }
```

taken from [SyncEngine](https://github.com/Starcounter/SyncEngine/blob/master/src/SyncEngine.Configurator/Api/UIHandlers.cs#L48-L62)

This proposal applies to all samples and prefabs, including HelloWorld.

@Starcounter/sc-apps WDYT?

**Comment by diliger** [comment]
I definitely like it more than Self.GET

**Comment by joozek78** [comment]
I agree that it's a better way to do it.
That said I don't even know what's the purpose of a `MasterPage` in most cases. See also https://github.com/Starcounter/level1/issues/4159

**Comment by per-samuelsson** [comment]
I'm trying to better understand this part of app development, and would like to ask a few novice questions:

1. There's always a master page? I mean, do we have sample of apps that don't have one? And if so, are such apps dependent on something like launcher to even expose themselves?
2. Master page == standalone page? And both are just terms kind of coined by us, even though somewhat standard? If so, isn't "index page" even more commonly used? Or is that more from old static web sites? No matter what: I think one thing we should do is to use **one** term in all our samples / prefabs.

**Comment by joozek78** [comment]
I just wanted to add, that https://github.com/Starcounter/level1/issues/4159 is currently on the way to obsolete the need for MasterPage (at least in most of cases)

**Comment by warpech** [comment]
As discussed on the today's App Architecture Task Force meeting (https://github.com/Starcounter/Minutes/issues/32):

The work on this is frozen after the release planning decides on the future of https://github.com/Starcounter/level1/issues/4159.

**Comment by warpech** [comment]
In response to @per-samuelsson questions:

# What is MasterPage?

Having some kind of `MasterPage` is the only way right now to switch views in your app, because we (Starcounter? `starcounter-include`?) cannot change the root Json response from an app within the same session.

Switching views is a very common pattern. For example, if your app has a list view and a detail view, you might want to switch from one to the other after a link is clicked. Clicking on the link replaces the view in your session.

With `MasterPage`, you create an instance of `MasterPage` once within a session. Switching between the views is achieved by setting a different JSON subtree as the value of `master.CurrentPage`.

You might ask - why on earth cannot I just replace what is the current JSON within the same session? I don't know. It might be a mix of reasons. From what I see, server actually sends the JSON to the client (though the operation is `add` and it should be `replace`). It seems that the problem actually might be in `starcounter-include`. I have created an issue: https://github.com/Starcounter/starcounter-include/issues/34

@tomalec could you try to investigate?

**Comment by joozek78** [comment]
> cannot change the root Json response from an app within the same session.

I might be mistaken, but I was under the impression I did that myself. Maybe I did change the root it was not optimal?

**Comment by warpech** [comment]
> I might be mistaken, but I was under the impression I did that myself. Maybe I did change the root it was not optimal?

For me this seems to be related to `starcounter-include` and switching between the same pages multiple times. Let's wait for the investigation of @tomalec.

**Comment by warpech** [comment]
Implementation of the pattern presented in the OP: https://github.com/StarcounterApps/Website/commit/63e5c3fd2d15ac064d7a0877b271507ff54a759c

Alternative proposal that uses a static method in the `MasterPage` class: https://github.com/StarcounterApps/Website/commit/b97e15d4b500ded56e751dadf9bfa5b6b10cbec0.

I like the first one more.

Let's discuss on the Monday's AppArchTF meeting.

**Comment by tomalec** [comment]
The issues seems to be cause by Website wrapping it in its own Masterpage. I suggested removing this wrapping anyways, but to pin the exact cause of the problem I would need some guidance on how Website works.

**Comment by warpech** [comment]
> The issues seems to be cause by Website wrapping it in its own Masterpage. I suggested removing this wrapping anyways, but to pin the exact cause of the problem I would need some guidance on how Website works.

I think it a wrong issue, isn't it?

**Comment by warpech** [comment]
On Monday's AppArchTF meeting it was agreed that the pattern from https://github.com/StarcounterApps/Website/commit/63e5c3fd2d15ac064d7a0877b271507ff54a759c will be implemented in all sample apps.

**Comment by warpech** [comment]
When this is done, verify that none of the same apps have things like: `LauncherWrapperPage`, `StandalonePage`.

**Comment by warpech** [comment]
Closing as done
