### ISSUE TITLE
Use interpolated strings in SQL queries

### ISSUE THREAD

**Issue by warpech** [Starcounter/Guidelines#25]
A remedy to hard-to-refactor SQL queries is to insert class and property names dynamically into the SQL strings using interpolation ([source](https://github.com/Starcounter/authorization/blob/b98ddfc2818e493bded36e0f17c8d83fc17861ca/Authorization/Partial/PermissionSelectionPartial.json.cs#L160-L164)):

```cs
Db.SQL<SomebodyGroup>(
    $"SELECT s FROM {typeof(SomebodyGroup).FullName} s WHERE s.{nameof(SomebodyGroup.Name)} LIKE ?",
    $"%{nameToLookFor.ToLowerInvariant()}%")
```

Does anyone disagree that this is the best practice in writing SQL queries now? I want to put that in the guidelines under a new page (SQL).

**Comment by warpech** [comment]
cc @Starcounter/sc-apps

**Comment by joozek78** [comment]
I would just remove this fragment from example: `$"%{nameToLookFor.ToLowerInvariant()}%"` - it can cause some confusion, since it uses string interpolation, but it's not what this guideline is about

**Comment by warpech** [comment]
As @k-rus points out in https://github.com/Starcounter/RebelsLounge/issues/111#issuecomment-300453167, `typeof()` executes at run time, not compile time. That is slow.

On the other hand, `nameof()` executes at compile time. But it does not look as attractive:

```c#
Db.SQL<SomebodyGroup>(
    $"SELECT s FROM {nameof(Simplified)}.{nameof(Ring2)}.{nameof(SomebodyGroup)} s WHERE s.{nameof(SomebodyGroup.Name)} LIKE ?", obj)
```

Suggestions?

**Comment by k-rus** [comment]
> As @k-rus points out in Starcounter/RebelsLounge#111 (comment), typeof() executes at run time, not compile time. That is slow.

You might already mean this, but I explicitly add that it is not just `typeof`, but also the string construction at runtime is expensive.

**Comment by joozek78** [comment]
let's focus on having valid code first, then think about performance

**Comment by warpech** [comment]
Do you mean there is something wrong with that code? All three options are valid code:

Executes at compile time:

```cs
Db.SQL<SomebodyGroup>($"SELECT s FROM Simplified.Ring2.SomebodyGroup s 
WHERE s.Name LIKE ?", obj)
```

Executes at run time:

```cs
Db.SQL<SomebodyGroup>($"SELECT s FROM {typeof(SomebodyGroup).FullName} s 
WHERE s.{nameof(SomebodyGroup.Name)} LIKE ?", obj)
```

Executes at compile time:

```cs
Db.SQL<SomebodyGroup>($"SELECT s FROM 
{nameof(Simplified)}.{nameof(Ring2)}.{nameof(SomebodyGroup)} s 
WHERE s.{nameof(SomebodyGroup.Name)} LIKE ?", obj)
```

**Comment by joozek78** [comment]
I mean that our primary focus should be promoting code that won't break easily, performance should be second thing to address.

The first snippet is extremely brittle when it comes to renaming database classes. 

Third snippet on the other hand is long at tedious to write (especially with longer namespaces) and could be discouraging. It is also brittle, if you move `SomebodyGroup` to a different ring the code could still compile (provided it had the usings necessary).

**Comment by Mackiovello** [comment]
I don't believe this is a good idea for two reasons:
1. It's much harder to read the interpolated queries. This is quite a big deal. We're used to reading normal SQL queries. This variation is quite different which makes it much more unnatural to read.
2. This will be wildly confusing for those that are new to Starcounter. "Why do they say they support SQL when you have to do all this interpolation"? Again, normal SQL syntax is familiar, this is not. It would also mean that the documented queries would be different from those that we have in our code. That's confusing. It's similar to the same situation we have with literals. 

I believe there's a middle-of-the-road solution to this. Interpolation should be used in prefab and other apps that are used in production for robustness. Sample apps, on the other hand, should use the old familiar SQL syntax. The docs should also stay with the old syntax.

**Comment by joozek78** [comment]
String interpolation is vanilla C#, we should assume that every C#
developer knows that

**Comment by k-rus** [comment]
Actually plain SQL example can be simplified to use only short name, like option 2:

```c#
Db.SQL<SomebodyGroup>("SELECT s FROMSomebodyGroup s WHERE s.Name LIKE ?", obj)
```

I don't know how high is performance penalty in option 2. If it will be too high in some cases, then the behaviour of entire application can be treated as unacceptable.

**Comment by joozek78** [comment]
Let's step back a bit here. Are you really saying that `typeof` is the real problem here? I thought what @k-rus pointed out was about string concatenation?

**Comment by joozek78** [comment]
And BTW string interpolation shouldn't hurt performance that much. Let's not optimize before we measure

**Comment by warpech** [comment]
In my opinion the below example:

```cs
Db.SQL<SomebodyGroup>($"SELECT s FROM {typeof(SomebodyGroup).FullName} s 
WHERE s.{nameof(SomebodyGroup.Name)} LIKE ?", obj)
```

is the best, because it is optimised for the minimum programmer error. For performance critical parts, it should not be used. The developer who writes performance critical code should know that. He can learn that from a C# book, not from Starcounter documentation.

---

You can play with the below link to see how are string interpolation, `nameof` and `typeof` compiled:

https://tryroslyn.azurewebsites.net/#b:master/K4Zwlgdg5gBAygTxAFwKYFsDcBYAUAB2ACMAbMAYxnJIEMQQYAxAe2bwG88ZuZDSKYAN2ZgAJjABCNAE4AKAJRcenXDzUwAwswghmJVADoA6tLBoAMpFSyAJACJ2EGulTMAZrJbN5AXzvycVXVuLR09QxMzVEsIa3t2ZAR8Vw8veQNGYBISADlnVD8ApW4fPB8gA

----

> Actually plain SQL example can be simplified to use only short name, like option 2:

Sorry @k-rus, that does not work. Short table names only work if the table is in the same namespace as the current class. In this case, it will fail:

![2017-05-11 15_54_07-helloworld debugging - microsoft visual studio](https://cloud.githubusercontent.com/assets/566463/25952861/1b32fd60-3662-11e7-8a89-87990fb60572.png)

**Comment by mmnosek** [comment]
I would like to add some more input on some arguments:

> It's much harder to read the interpolated queries. This is quite a big deal. We're used to reading normal SQL queries. This variation is quite different which makes it much more unnatural to read.

Most of the SQL queries in Starcounter apps are simple. You don't need to scroll, write hundreds of lines etc. So a little bit more code is not a big deal IMO. Especially for experienced developers. Usually, we don't do joins etc. So even if it's a little bit less readable at the first sight, benefits are more important: refactoring easy and references to the classes are checked in compile time. I've spent a lot of time debugging this kind of problems. Using interpolated queries let us avoid most of the errors when a query is executed. This is a real problem - that only when we execute a query we can discover issues.

> This will be wildly confusing for those that are new to Starcounter. "Why do they say they support SQL when you have to do all this interpolation"? Again, normal SQL syntax is familiar, this is not. It would also mean that the documented queries would be different from those that we have in our code. That's confusing. It's similar to the same situation we have with literals.

I do not agree. I've had an opportunity to explain and show Starcounter to different kind of developers. As they see SQL as a string, most of them immediately ask: What if we'll change namespace, class or we make a typo here? It will be a mess.
When I explain that we are aware of this problem and we have a workaround for it (interpolated strings with `typeof`, `nameof` etc.) all of them are happy with the solution and agree that it's a better solution.

**Comment by Mackiovello** [comment]
You've convinced me @mmnosek. That's a really good argument.

**Comment by miyconst** [comment]
One thing seems to be forgotten here: escaping SQL keywords. With plain SQL it's not a problem, with string interpolation starting to get a bit more tricky.

Example:

```cs
Db.SQL("SELECT * FROM Customer.\"Order\"");
```

```cs
Db.SQL($"SELECT * FROM \"{typeof(Customer).FullName.Replace(".", "\".\"")}\"");
```

While string interpolation brings a performance penalty, the string replacement brings even more.

**Comment by joozek78** [comment]
Actually escaping whole name should also work:

```c#
Db.SQL($"SELECT * FROM \"{typeof(Customer).FullName}\"");

**Comment by miyconst** [comment]
It works in the new query processor, not in the old one, as far as I know.

**Comment by joozek78** [comment]
What do you mean "the old one"? I used it in 2.3.1

**Comment by miyconst** [comment]
>What do you mean "the old one"? I used it in 2.3.1

The old one means the current one, and the new one is in the development.

If escaping entire string works in `2.3.1`, then it's good. I remember it was not working some long time ago.

**Comment by miyconst** [comment]
>Actually escaping whole name should also work:

It does not work in `2.3.0`.

```sql
SELECT *
FROM "Starcounter.Metadata.Index"
```

Fails with:

```
Unknown delimited identifier with dot View the log for more details.
```

**Comment by k-rus** [comment]
Double quoting means single identifiter, so if it works to cover all identifiers at once, then it is a bug.

**Comment by k-rus** [comment]
> Double quoting means single identifiter, so if it works to cover all identifiers at once, then it is a bug.

The actual issue on this is https://github.com/Starcounter/level1/issues/1882

**Comment by joozek78** [comment]
Wow, that sounds inconvenient. I'm not sure I fully understand the thread
you referenced? Can't we also accept quoting identifiers along with
namespace? That would be intuitive

**Comment by k-rus** [comment]
> Wow, that sounds inconvenient. I'm not sure I fully understand the thread
> you referenced? Can't we also accept quoting identifiers along with
> namespace? That would be intuitive

No, each identifier should be double quoted (it was fixed in https://github.com/Starcounter/level1/issues/2402). This allows to use more symbols in identifiers, including dot. However, I am not fully certain if it will actually work with dynamic types. The discussion can be continued in Starcounter/level1#1882 and should take in account not just short time current need.

**Comment by warpech** [comment]
The advice from this thread was added to the guidelines in PR #44
