### ISSUE TITLE
Move things that are not Starcounter Apps opinion to Docs Cookbook

### ISSUE THREAD

**Issue by warpech** [Starcounter/Guidelines#28]
As discussed on the todays App Architecture Task Force meeting (https://github.com/Starcounter/Minutes/issues/32): 

Some of the articles in the Guidelines should be moved to the Cookbook at `docs.starcounter.io`. 
 Namely:

- https://starcounter.gitbooks.io/guidelines/content/app-icon.html
- https://starcounter.gitbooks.io/guidelines/content/icons.html
- https://starcounter.gitbooks.io/guidelines/content/project_structure.html

All other pages I think should stay in Guidelines because they express our opinion in naming, etc.

**Comment by warpech** [comment]
Project structure should be moved under a title "Proposed project structure", with some explanation.

It should match the boilerplate at https://github.com/Starcounter/Starcounter.VisualStudio/tree/master/src/Starcounter.VS.CSBasicApplicationProjectTemplate

**Comment by Mackiovello** [comment]
This is now done. Made some minor changes to the pages and published them.

https://docs.starcounter.io/v/Develop/cookbook/icons/
https://docs.starcounter.io/v/Develop/cookbook/project-structure/

**Comment by warpech** [comment]
Thank you @Mackiovello, you're a godsend!
