### ISSUE TITLE
Is there any reason not to use C#7?

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Guidelines#29]
C#7 is around for some time, it has a lot of cool features. Do we have any reason not to use it? I mean potential compatibility issues, weaver, customers, etc.
@Starcounter/sc-apps

**Comment by warpech** [comment]
We are already using C# 7.0 in some of the sample apps, but developers who do not have it installed are seeing syntax errors. 

See: https://github.com/StarcounterApps/KitchenSink/pull/136/files/ea913a20027c9fdaee3a623dcfca3eb666191163#diff-c78c41f3c1aefc3c41ccd0562ae54958

I read somewhere that setting .Net 4.7 as the required version in sample apps would make it automatically compatible with C# 7.0. Is there any flaw in my thinking? @Mackiovello, @mmnosek, @dan31, @ubbeK 

Of course that isolates the developers who do not have .Net 4.7, but they can overcome it by installing .Net 4.7 when they are prompted about it.

**Comment by joozek78** [comment]
> I read somewhere that setting .Net 4.7 as the required version in sample apps would make it automatically compatible with C# 7.0. Is there any flaw in my thinking?

I think yes :) Requiring .net 4.7 is not required to use C#7

**Comment by warpech** [comment]
Testing with @alshakero proved that I was wrong. Installing .Net Developer Pack 4.6.2 or 4.7 does not give you C# 7.0 compilation abilities in VS 2015.

Adding https://www.nuget.org/packages/Microsoft.Net.Compilers/ to the project makes is possible to build C# 7.0 in VS 2015, but still you see syntax errors in Intellisense. There is no way to solve that other than installing VS 2015.

I propose that we just start using VS 2017 and C# 7.0. If you're getting syntax error then you need VS 2017.

**Comment by warpech** [comment]
After sleeping on this for few nights, I think that we are making people a favour by introducing them to C# 7.0. Let's use C# 7.0 freely in our apps.

**Comment by warpech** [comment]
Related: https://github.com/StarcounterApps/KitchenSink/issues/146

**Comment by warpech** [comment]
C# 7 was added as a recommendation to our guidelines in PR #44.
