### ISSUE TITLE
Update bat scripts in StarcounterApps

### ISSUE THREAD

**Issue by warpech** [Starcounter/Guidelines#31]
PR https://github.com/Starcounter/Guidelines/pull/30 introduced a nice change to `run.bat`.

Scripts in https://github.com/StarcounterApps should be updated. Do we have a volunteer?

**Comment by Mihaiii** [comment]
I can take care of this and all other similar issues that might be in the future, if that's ok.

**Comment by warpech** [comment]
Great, thanks! Please do such changes as PRs. @Mackiovello could you pls be the reviewer?

**Comment by Mackiovello** [comment]
> @Mackiovello could you pls be the reviewer?

I can do that

**Comment by warpech** [comment]
Great job, thank you so much @Mihaiii and @Mackiovello! 🙌
