### ISSUE TITLE
Pattern for the Settings page

### ISSUE THREAD

**Issue by warpech** [Starcounter/Guidelines#33]
"Settings page" was first presented in https://github.com/StarcounterAppsFreezer/Launcher/issues/177, the later asked for clarifications in https://github.com/Starcounter/RebelsLounge/issues/29, finally dismissed in https://github.com/Starcounter/TechComm/issues/171...

We have quite a love/hate relationship with what used to be called a "Settings page" in Launcher. Now it may look like we've abandoned the idea, but I think that we still need a common concept of a Settings page.

Consider systems like Android ("Settings" app), Windows ("Control Panel" prior to Win 10, "Settings" in Win 10), MacOS ("System Preferences"), Google (G Suite [Admin Console](https://admin.google.com/), Google.com [My Account](https://myaccount.google.com/))... All these systems have a single place in which you configure the behaviour of your system.

I think that we need the same! 

It should be based on few principles:

- each app has a conventional URI `/<appname>/settings` (not enforced)
- if you want, you can make it appear in the shared Settings page by mapping it to the ~~class `SettingsBlendingPoint` : `Simplified.Ring6.WebSection`~~ token `settings`
- Launchpad has a built-in icon and link to `/launchpad/settings`, which itself is mapped to ~~`SettingsBlendingPoint`~~ `settings`
- ~~if you are not using Simplified data model then you need to have a equivalent of the `SettingsBlendingPoint` class in your data model and map that class to `SettingsBlendingPoint` using the data mapping~~

The above would gives you a big merged page of settings coming from all apps. It does not look nice. I believe that some kind of accordion or other UI can be achieved on the client-side by a custom element.

Any comments?

cc @Starcounter/sc-apps

**Comment by mmnosek** [comment]
What can I add, great idea! Eventually, I think about separate "Settings App". I don't know what additional features it should have, yet.

**Comment by warpech** [comment]
@tomalec something to add from blending perspective? If not, I will discuss this in App Arch TF and implement if approved.

**Comment by tomalec** [comment]
nothing to add, I really like this idea

**Comment by warpech** [comment]
I have added ~~strikethrough~~ in the OP for the items that should not be implemented right now. Before we have blending contexts (https://github.com/Starcounter/RebelsLounge/issues/126) we should stick to the currently used blending token `settings`.

**Comment by warpech** [comment]
To implement this, there are two parts:

1. Launchpad link: https://github.com/StarcounterApps/Launchpad/issues/18
2. Explanation of the pattern: https://github.com/Starcounter/Docs/issues/121

**Comment by warpech** [comment]
Both parts now implemented. Closing as done.
