### ISSUE TITLE
Requirements and recommendations for frameworks/libraries/...

### ISSUE THREAD

**Issue by ubbeK** [Starcounter/Guidelines#34]
I would like to propose a new guideline page which should contain requirements/recommendations for

- 3rd party libraries
- frameworks
- language versions
- IDE
- compilers

All apps, scripts, tools, build environments and so on should support/use at least these versions or use specific libraries.

For instance:
commandline api: use Mircosoft.Extensions.CommandLineUtils version X.Y.Y or higher
json: NewtonSoft.JSON version X.Y.Y or higher
.NET Core ...
.NET Framework ...
C# ...
VisualStudio ...
CMake ...
Python ...

There are plenty more to add, please let me know.

What do you think? Is this something we could manage in order converge the number of frameworks and libraries, and to have definite answers for questions like these https://github.com/Starcounter/Guidelines/issues/29

@dan31 @Mackiovello @miyconst @mmnosek @alemoi @warpech @Joltrix @joozek78 @chrhol @henriksjostrom @linkdata @andwah @k-rus @per-samuelsson @tomalec

**Comment by warpech** [comment]
Do you mean this for our internal use? I think it is a good call! It could save us from problems like:

- https://github.com/Starcounter/CompanyTrack/issues/346#issuecomment-310304129
- https://github.com/StarcounterApps/KitchenSink/issues/146

Just note that, as @k-rus always points out, different teams might have different configs.

@joozek78 has written some of his recommendations in https://github.com/Starcounter/AdminTrack/blob/master/new_employee.md (for example, "Visual Studio extensions"). Maybe just extend that page to your liking? Setup recommendations can be moved to a separate file.

**Comment by ubbeK** [comment]
> Do you mean this for our internal use?

Yes, for internal use.

> Just note that, as @k-rus always points out, different teams might have different configs.

If we ever are going to have a clean/agile build environment with low setup time we have to be more strict in certain areas. This is definitely one of them.

**Comment by ubbeK** [comment]
Issue moved to [Starcounter/AdminTrack #295](https://github.com/Starcounter/AdminTrack/issues/295) via [**ZenHub**](https://www.zenhub.com/)
