### ISSUE TITLE
Add HTML code formatting page

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Guidelines#4]

**Comment by warpech** [comment]
@miyconst what are the guidelines that you wanted to add? Maybe @Mackiovello can put it to words?

**Comment by warpech** [comment]
What I would like to see there:

- always import what you are using in the view partials (including Polymer, if you're using `dom-bind`)
- put everything that is executed once outside of `<template>`
- always provide `declarative-shadow-dom` part and slot names, even when you're not using it

**Comment by warpech** [comment]
@tomalec can you pls help out here? Do we have formatting suggestions for HTML? Proposed `.editorconfig`?

**Comment by warpech** [comment]
Ping @tomalec, @miyconst. What is the formatting suggestion that you would like to use? I am asking because personally I don't give a damn, but I would like to have a recommendation for the new team members.

**Comment by tomalec** [comment]
> - always provide `declarative-shadow-dom` part and slot names, even when you're not using it

I'd rather say 
> - provide (replacable) layout in `declarative-shadow-dom`, if you have one,
> - provide slot names, even when you are not using them.

**Comment by warpech** [comment]
Any opinion regarding the indentation? Visual Studio uses 4 spaces by default.

Example:

```html
<body>
    <div>
        <span></span>
    </div>
</body>
```

I would keep it like that.

**Comment by warpech** [comment]
Implemented in https://github.com/Starcounter/Guidelines/pull/42

**Comment by warpech** [comment]
Closing as done
