### ISSUE TITLE
App icons should be SVG

### ISSUE THREAD

**Issue by warpech** [Starcounter/Guidelines#41]
Right now, most of the apps have a PNG iccn in the view that is mapped to `app-name` to produce the icon for Launchpad (`AppName.html` or `AppIcon.html`).

A notable exception is CssVariablesManager, which has an SVG icon: https://github.com/StarcounterApps/CssVariablesManager/blob/4aad5186522a6297bc4ca7f713d91424220d6552/src/CssVariablesManager/wwwroot/CssVariablesManager/AppIcon.html

All apps in https://github.com/StarcounterApps should be migrated to have an SVG icon.

**Comment by Mihaiii** [comment]
I think that everything was covered.
@Starcounter/sc-apps who can review?
Please use https://github.com/StarcounterApps/Launchpad/pull/23/commits/be2ccfd5d63a4185ff287671b0eae8e0abb031a6 when testing.

**Comment by habib535** [comment]
The functionality works fine but I can see that not all SVG are of the same size. For example viewBox="0 0 64 64" in Cashier and viewBox="0 0 32 32" in Search. Although in Launchpad they render the same size because of parent class CSS.

**Comment by Mihaiii** [comment]
Closing as done.

**Comment by warpech** [comment]
Few icons in Calendar still use PNG: https://github.com/StarcounterApps/Calendar/blob/55722cd0a35b4fbaf4e2ab7a7ea12852d8b30f53/src/Calendar/wwwroot/Calendar/viewmodels/IconPage.html

Other than that, it looks that it is all done! Thanks
