### ISSUE TITLE
Every app should have an issue template

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Guidelines#48]
As I found out recently, not every our currently maintaining applications has issue template in it. I suggest to add them to every app and to mention this in guidelines (with example template), that every new app should have an issue template for easier and more organized reporting.

cc @Starcounter/sc-apps

**Comment by un-tone** [comment]
I suggest to not only add but refresh the existing issue templates since many of them contain an obsolete info, for example incorrect Organizations:
```
 - StarcounterPrefabs/Launcher@5.0.0
 - StarcounterSamples/Products@c85359e40caea2b9143f31121c1fb54b4bb549df
```

**Comment by PatrykSzwer** [comment]
Created new issue template file for apps:
- https://github.com/StarcounterApps/AutoAuditSuite
- https://github.com/StarcounterApps/Notes
- https://github.com/StarcounterApps/Timeline
- https://github.com/StarcounterApps/Simplified
- https://github.com/StarcounterApps/Launchpad
- https://github.com/StarcounterApps/SampleWebsiteTheme
- https://github.com/StarcounterApps/CssVariablesManager
- https://github.com/StarcounterApps/DisplayAppTitle
- https://github.com/StarcounterApps/HelloWorld

Updated existed template for:
- https://github.com/StarcounterApps/Website
- https://github.com/StarcounterApps/SignIn
- https://github.com/StarcounterApps/Content
- https://github.com/StarcounterApps/Products
- https://github.com/StarcounterApps/People
- https://github.com/StarcounterApps/Calendar
- https://github.com/StarcounterApps/Search
- https://github.com/StarcounterApps/CompositionEditor
- https://github.com/StarcounterApps/Chatter
- https://github.com/StarcounterApps/Cashier
- https://github.com/StarcounterApps/Barcodes
- https://github.com/StarcounterApps/Images
- https://github.com/StarcounterApps/UserAdmin
- https://github.com/StarcounterApps/CompositionProvider
- https://github.com/StarcounterApps/Skyper
- https://github.com/StarcounterApps/KitchenSink

I think thats all apps that needs new/updated issue template. I'll close this issue, if You found out that any other repository needs it, feel free to reopen.

**Comment by warpech** [comment]
@PatrykSzwer you did this change on `master` branch, which is good, but it causes diverging of the branches `master` and `develop`. 

`develop` should be always ahead or equal `master`, never behind it.

Could you pls fix it by merging `master` to `develop` in all these repos?

**Comment by PatrykSzwer** [comment]
FYI I didn't know how should I do merging in https://github.com/StarcounterApps/HelloWorld app, since there is no develop branch. If I have to merge changes to one of those tutorial-xxx branches please let me know.

**Comment by warpech** [comment]
HelloWorld is special, see the info about branches and commits here: https://github.com/StarcounterApps/HelloWorld/wiki

Whenever you'd like to make changes in this repo, pls talk to @Mackiovello

**Comment by Mackiovello** [comment]
I've added an issue template to HelloWorld. Since there's only https://github.com/StarcounterApps/SignIn/pull/138 left, I'll close this issue
