### ISSUE TITLE
Updated way to create MasterPage and Session 

### ISSUE THREAD

**Issue by Mackiovello** [Starcounter/Guidelines#49]
With the changes to session the common way to create MasterPage and Session from https://github.com/Starcounter/Guidelines/issues/23 no longer applies: 
```cs
protected MasterPage GetMasterFromSession()
{
    if (Session.Current == null)
    {
        Session.Current = new Session(SessionOptions.PatchVersioning);
    }

    var master = Session.Current.Data as MasterPage;

    if (master == null)
    {
        master = new MasterPage();
        Session.Current.Data = master;
    }

    return master;
}
```

The updated way should look something like this:
```cs
protected MasterPage GetMasterPageFromSession()
{
    var session = Session.Ensure();

    var master = session.Store[nameof(MasterPage)] as MasterPage ?? new MasterPage();

    session.Store[nameof(MasterPage)] = master;
            
    return master;
}
```

Is that right? cc @warpech

**Comment by Mihaiii** [comment]
I haven't covered DisplayAppTitle - like I said before, it doesn't build on `master` branch, please fix that problem first.
Other than that, I covered everything that was left.
Closing.

**Comment by warpech** [comment]
Thanks @Mihaiii! I have created a separate issue for that: https://github.com/Starcounter/DisplayAppTitle/issues/3
