### ISSUE TITLE
Update batch files

### ISSUE THREAD

**Issue by Mihaiii** [Starcounter/Guidelines#51]
Related with https://github.com/Starcounter/Guidelines/pull/50 .

**Comment by Mihaiii** [comment]
@Starcounter/sc-apps , please review.

Build fails on `master` branch for DisplayAppTitle.

**Comment by Mackiovello** [comment]
@Mihaiii, by asking everyone, you're essentially asking no one. I'm going through the remaining pull requests so we can close this one

**Comment by Mihaiii** [comment]
Thanks.
Closing as done.
