### ISSUE TITLE
Uniform batch scripts in all apps

### ISSUE THREAD

**Issue by warpech** [Starcounter/Guidelines#6]
In some of the repos we have the following files:

- build.bat
- test.bat
- run.bat
- package.bat
- make.bat
- restart.bat

They are in various locations:

- `/` (solution root)
- `/src/<appname>` (project root)
- `/tools` (tools subdirectory)

I would like to unify this. My proposal is:

# Location

The batch files should always be in the solution root, because the reason for their existence is to simplify some operations.

# test.bat

Keep this file. Sample: https://github.com/StarcounterPrefabs/Launcher/blob/master/launcher_selenium_test.bat

# run.bat

Keep this file. Sample: https://github.com/StarcounterPrefabs/Launcher/blob/master/run.bat

# build.bat

Perhaps remove this file? The same can be achieved by:

```
msbuild HelloWorld.sln
```

This will only work if `msbuild` 14.0 is in your PATH. If it is not, add it using `SET PATH=C:\Program Files (x86)\MSBuild\14.0\Bin\;%PATH%`

Drawback: it will not be possible by double-clicking in Windows Explorer. I am sometimes using this method, which is why I have doubts if this is good or not.

Alternative: keep build.bat that looks like below:

```
@echo off
"C:\Program Files (x86)\MSBuild\14.0\Bin\msbuild" HelloWorld.sln
```

# package.bat

Remove this file. The same can be achieved by:

```
cd src\HelloWorld
starpack -p
```

# make.bat

Remove this file. The same can be achieved by building and packaging (see above)

# restart.bat

Remove this file. The same can be achieved by `staradmin stop db default` and `run.bat`

@miyconst, @Mackiovello, @joozek78, @mmnosek, @aloscha, @ubbeK, @Joltrix  WDYT?

**Comment by warpech** [comment]
I have changed my proposal regarding build.bat. I need some peer opinion on one way or another.

cc @diliger

**Comment by joozek78** [comment]
Why use rebuild target?

**Comment by warpech** [comment]
Because sometimes there are some cached compiled `json.g.cs` files that cause errors when building. I had never nailed down what is the actual reason - I am just using Rebuild or Clean, Build because it always works.

I agree that it is better to fix the root of the problem, so let's remove `/t:Rebuild` from build.bat.

**Comment by ubbeK** [comment]
@warpech Good initiative!

> The batch files should always be in the solution root, because the reason for their existence is to simplify some operations.

Agree!

> This will only work if msbuild 14.0 is in your PATH. If it is not, add it using SET PATH=C:\Program Files (x86)\MSBuild\14.0\Bin\;%PATH%

I prefer to check if `VS140COMNTOOLS` exists as an enviroment variable and call `%VS140COMNTOOLS%vsvars32.bat` if it does. Then there is no problem to execute `msbuild "!currentDir!\AppSolution.sln" /t:Rebuild`.

**Comment by aloscha** [comment]
>cd src\HelloWorld
starpack -p

WDYT @warpech  that  all apps start support starpack, so when we have automatic deploymeny, we just call some `bat` file that makes zip from starpack? (and maybe something more in bat if maker add sth)

**Comment by warpech** [comment]
@ubbeK, I didn't know about this, nice! But if I have to write this every time I open cmd:

```
"%VS140COMNTOOLS%\vsvars32.bat"
msbuild HelloWorld.sln
```

Then I really prefer `build.bat` that does it for me.

> WDYT @warpech that all apps start support starpack, so when we have automatic deploymeny, we just call some bat file that makes zip from starpack? (and maybe something more in bat if maker add sth)

`starpack -p` makes the zip. What I mean is that there is little benefit of having a bat file that just calls `starpack -p`.

**Comment by aloscha** [comment]
What if we need to add there something more? I mean if we have standard to create build.bat than I don't need to think, I just call it :)

**Comment by warpech** [comment]
Sure, I think there should be a batch file for any batch work. But here's a definition of the word batch:

> a group of records processed as a single unit, usually without input from a user.

A single line call is hardly a "batch". I would like to have batch files only for operations that consist of multiple commands, or single complex command.

**Comment by ubbeK** [comment]
> @ubbeK, I didn't know about this, nice! But if I have to write this every time I open cmd:
> 
> "%VS140COMNTOOLS%\vsvars32.bat"
> msbuild HelloWorld.sln
> Then I really prefer build.bat that does it for me.

Sure. Every msbuild has their own VSXX0COMNTOOLS.
VS2012 -> VS120COMNTOOLS
VS2013 -> VS130COMNTOOLS
VS2015 -> VS140COMNTOOLS
and guessing VS2017 -> VS150COMNTOOLS
it is an easy way to figure out what versions of VS are installed. 

By running the `vsvars32.bat` you get the same setup as `Developer Command prompt for VS`

**Comment by warpech** [comment]
My final proposal is below (using Launcher as the example). Please comment.

# test.bat

Keep as:

```
@ECHO OFF

:: If we are not running on build server, stop the db to stop the running apps
IF NOT "% SC_RUNNING_ON_BUILD_SERVER%"=="True" (
    staradmin stop db default
)

IF "%CONFIGURATION%"=="" SET CONFIGURATION=Debug

star --resourcedir="%~dp0src\Launcher\wwwroot" "%~dp0bin/%Configuration%/Launcher.exe"
IF ERRORLEVEL 1 EXIT /B 1

star --resourcedir="%~dp0test\Launcher_AcceptanceHelperOne\wwwroot" "%~dp0test/Launcher_AcceptanceHelperOne/bin/%Configuration%/Launcher_AcceptanceHelperOne.exe"
IF ERRORLEVEL 1 EXIT /B 1

star --resourcedir="%~dp0test\Launcher_AcceptanceHelperTwo\wwwroot" "%~dp0test/Launcher_AcceptanceHelperTwo/bin/%Configuration%/Launcher_AcceptanceHelperTwo.exe"
IF ERRORLEVEL 1 EXIT /B 1

IF NOT EXIST "packages\NUnit.ConsoleRunner.3.2.0\" (ECHO Error: Cannot find NUnit Console Runner. Build the project to restore the packages && EXIT /B 1)
packages\NUnit.ConsoleRunner.3.2.0\tools\nunit3-console.exe test\Launcher_AcceptanceTest\Launcher_AcceptanceTest.csproj /config:%Configuration%
IF ERRORLEVEL 1 EXIT /B 1
```

# run.bat

Keep as:

```
@ECHO OFF

IF "%Configuration%"=="" set Configuration=Debug

star --resourcedir="%~dp0src\Launcher\wwwroot" "%~dp0bin/%Configuration%/Launcher.exe"
```

# build.bat

```
@ECHO OFF

:: Set up the env to use Msbuild 14.0
CALL "%VS140COMNTOOLS%\vsvars32.bat"

:: Try to restore packages
WHERE nuget.exe >nul 2>nul
IF %ERRORLEVEL% EQU 0 nuget.exe restore
IF NOT EXIST "packages\" (ECHO Error: Get nuget.exe or build the sln in VS to restore the packages && EXIT /B 1)

msbuild
```

# package.bat

Keep as:

```
cd src\Launcher
starpack -p
```

In future this might grow to include bumping of the version number.

# make.bat, restart.bat

Remove the files.

**Comment by joozek78** [comment]
instead of `%SC_RUNNING_ON_BUILDSERVER%` we could just use `%
TEAMCITY_VERSION%`

**Comment by joozek78** [comment]
instead of `%SC_RUNNING_ON_BUILDSERVER%` we could just use `%
TEAMCITY_VERSION%`

**Comment by ubbeK** [comment]
It looks good!

Maybe add some error handling for checking correct VS-tool environment variable
```bat
IF [%VS140COMNTOOLS%] EQU [] ( 
    set "msgError=some error message (VS2015 is probably not installed)"
    set ERRORLEVEL=2
    GOTO ERROR
) ELSE (
    call "%VS140COMNTOOLS%vsvars32.bat"
)
```

...

```bat
:ERROR
echo %msgError%
exit /b %ERRORLEVEL%
:END
```

**Comment by warpech** [comment]
Another change needed - run in the same directory as the batch file:

```
PUSHD %~dp0
msbuild
POPD
GOTO END
```

**Comment by warpech** [comment]
Anyone knows how to run the following lines:

```
:: Try to restore packages
WHERE nuget.exe >nul 2>nul
IF %ERRORLEVEL% EQU 0 nuget.exe restore
IF NOT EXIST "packages\" (ECHO Error: Get nuget.exe or build the sln in VS to restore the packages && EXIT /B 1)
```

Only when there is a `packages.config` file in any of the subdirs?

**Comment by ubbeK** [comment]
I haven't tried this out but something like this should work

```batch
IF %ERRORLEVEL% EQU 0 (
    for /d %%D in (*) do ( 
        IF EXIST %%~fD\packages.config (
            nuget.exe restore
            GOTO NUGETRESTORED
        )
    )
)
:NUGETRESTORED
```

Batch files are horrible to maintain. Another solution would be to use python scripts instead which @alemoi would agree on, but this adds a python dependency to the build system.

**Comment by joozek78** [comment]
Maybe powershell?

**Comment by warpech** [comment]
I'd rather not overdo it. Maybe just let's not include these lines in projects that don't have `packages.config`.

**Comment by ubbeK** [comment]
> I'd rather not overdo it. Maybe just let's not include these lines in projects that don't have packages.config.

Agreed!, I think python is a bad idea but some sort of loop as I wrote before might be worth it since then we may have the exact same files.

**Comment by warpech** [comment]
If you want to, but since we are talking about files located at `src/*/packages.confg`, I thought that this is a nested FOR loop, which is beyond my bat skills. If you find it feasible, please give it a try :) Maybe propose a PR to Launcher if it works?

**Comment by KmaTTi89** [comment]
@warpech 
My fixes proposals to test.bat and run.bat files.

test.bat
`@echo off

IF NOT EXIST "%~dp0packages\NUnit.ConsoleRunner.3.6.0\" (ECHO Error: Cannot find NUnit Console Runner. Build the project to restore the packages && PAUSE && EXIT /B 1)
%~dp0packages\NUnit.ConsoleRunner.3.6.0\tools\nunit3-console.exe %~dp0test\KitchenSink.Tests\bin\Debug\KitchenSink.Tests.dll --noheader --params Browsers=Chrome,Firefox
pause
IF ERRORLEVEL 1 EXIT /B 1`

- test.bat should only run test, not app and then test (name is test.bat not runAppAndTest.bat), user should call run.bat before test.bat
- if you want user to see ECHO Error, have to add PAUSE before EXIT
- if you want user to see test result, you have to add PAUSE before last line


run.bat
`@echo off

:: If we are not running on build server, stop the db to stop the running apps
IF NOT "%TEAMCITY_VERSION%"=="True" (
    staradmin stop db default
)

star.exe --resourcedir="%~dp0src\KitchenSink\wwwroot" "%~dp0bin\Debug\KitchenSink.exe"`

- there is %TEAMCITY_VERSION% var in TC build agent, we can use it to check if script is running on it

**Comment by ubbeK** [comment]
> %~dp0packages\NUnit.ConsoleRunner.3.6.0\

Isn't there another way to determind if the specified version of NUnit.ConsoleRunner exists? Hard coded versions is not a good idea since it has to be updated along with the package itself.

> - if you want user to see ECHO Error, have to add PAUSE before EXIT
> - if you want user to see test result, you have to add PAUSE before last line

not if it is run from the console.

**Comment by warpech** [comment]
Is there a way in the BAT file to know if it is run from the console?

**Comment by KmaTTi89** [comment]
Why we need that??

**Comment by warpech** [comment]
There are 2 ways to run a BAT script:

- from console (cmd) - here PAUSE is annoying and harmful
- from Windows Explorer - here PAUSE is useful

**Comment by KmaTTi89** [comment]
I now there are 2 ways to run a BAT script.
Can you show me how PAUSE is annoying and harmful when running script from console?

![image](https://cloud.githubusercontent.com/assets/25149662/23459812/5f34a9a4-fe82-11e6-8c16-33fedb106d42.png)

**Comment by joozek78** [comment]
Well, it makes it require interaction. You can't just run two of them one
after another (you have to press a key in between). That said, a simple
--non-interactive or --fast or other flag would probably make it okay

**Comment by warpech** [comment]
Renowned Unix principles, which are good for any console programs (not only Unix) have this among others: "Avoid captive user interfaces".

This means that your command line program should not break the world outside of it, because it might be used as part of a longer chains of programs.

Note that this applies to console programs and scripts, not to GUIs.

Every developer should be familiar with this on high level:

- https://en.wikipedia.org/wiki/Unix_philosophy
- http://www.faqs.org/docs/artu/ch01s06.html

**Comment by ubbeK** [comment]
> Is there a way in the BAT file to know if it is run from the console?

http://stackoverflow.com/questions/9419875/determining-if-batch-script-has-been-started-executed-from-the-command-line-cmd

**Comment by warpech** [comment]
Final proposal: https://starcounter.gitbooks.io/guidelines/content/batch-files.html

If there are no comments then we will propose to unify the scripts in the apps.

**Comment by ubbeK** [comment]
I approve

**Comment by warpech** [comment]
Closing then. If anyone has more comments, please reopen.

**Comment by Mackiovello** [comment]
Do we need `tools/nuget.exe` in all of our apps even thought there might not be any nuget dependencies?

Regarding Build.bat

@ubbeK and I discussed this

**Comment by warpech** [comment]
> Do we need `tools/nuget.exe` in all of our apps even thought there might not be any nuget dependencies?

No, it is only needed when `build.bat` uses it. And that should be only if there are any NuGet dependencies in the sln.

**Comment by Mackiovello** [comment]
> No, it is only needed when build.bat uses it. And that should be only if there are any NuGet dependencies in the sln.

Got it. So this should be removed when it does not contain any NuGet dependencies:

```
:: Try to restore packages. This is only needed when the solution depends on NuGet packages
PUSHD %~dp0\tools
WHERE nuget.exe >nul 2>nul
IF %ERRORLEVEL% EQU 0 nuget.exe restore ..
IF NOT EXIST "..\packages\" (ECHO Error: Get nuget.exe or build the sln in VS to restore the packages && EXIT /B 1)
POPD
```

Also, regarding the tests: should there be a `test.bat` file if the solution doesn't contain any test projects? For example, Barcodes contains [`test.js`](https://github.com/StarcounterApps/Barcodes/blob/master/test/test.js) which can't be run with the current `test.bat`.

**Comment by warpech** [comment]
> So this should be removed when it does not contain any NuGet dependencies

Yes

> should there be a `test.bat` file if the solution doesn't contain any test projects?

No if there are no test projects. If there is a JavaScript test project, then `test.bat` should be adjusted to run that test.

I have updated https://starcounter.gitbooks.io/guidelines/content/batch-files.html to cover that

**Comment by Mackiovello** [comment]
Closing as the question was addressed.

**Comment by warpech** [comment]
As proposed by @joozek78 in https://github.com/StarcounterApps/SignIn/pull/75#discussion_r106898315, I have changed **package.bat** to use PUSHD/POPD to properly work when called from an external directory.
