### ISSUE TITLE
Private properties and fields in _camelCase

### ISSUE THREAD

**Issue by warpech** [Starcounter/Guidelines#8]
I have overlooked one thing. Both [corefx](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md) and [aspnet](https://github.com/aspnet/Home/wiki/Engineering-guidelines) guidelines recommend naming private fields and props like `_camelCase`.

Our [Guidelines](https://starcounter.gitbooks.io/guidelines/content/coding_style/csharp_code_formatting.html) say it should be `PascalCase`.

If no objections, I will switch the recommendation to `_camelCase` in our guidelines.

cc @miyconst, @Mackiovello, @joozek78, @mmnosek, @aloscha, @ubbeK, @Joltrix, @KmaTTi89, @diliger

**Comment by miyconst** [comment]
>If no objections, I will switch the recommendation to `_camelCase` in our guidelines.

Switch it to `camelCase` and no objections from me.

**Comment by warpech** [comment]
Why do you object `_`?

**Comment by miyconst** [comment]
>Very disagree. The `_` is an evil. C# is a language after all, and that means a human should be able to read it. Try to read the following and you will see which one is more "readable".

```
_name = name;
this.Name = name;
```

From my [comment](https://github.com/StarcounterPrefabs/Guidelines/issues/5#issuecomment-271837769) on the main thread.

**Comment by warpech** [comment]
I read the above example as:

- the first line is a private property that's missing the `this.` keyword
- the second line is a public property

**Comment by miyconst** [comment]
Let's change it, since we decided not to use `PascalCase` for the private fields.

```cs
_name = name;
this.name = name;
```

But this was not the point, just try to pronounce the lines.

**Comment by joozek78** [comment]
I think that underscore notation is fine. Why deviate from something that
is recommended and used everywhere?

**Comment by diliger** [comment]
I agree with @miyconst about underscore.
And for private/protected properties/fields more used to `camelCase` as proposed.

**Comment by miyconst** [comment]
>I think that underscore notation is fine. Why deviate from something that
is recommended and used everywhere?

This is just my personal opinion, I hate to type and read code with `_`, but if entire team is up for it, I am willing to adopt `_` as well.

**Comment by ubbeK** [comment]
> This is just my personal opinion, I hate to type and read code with _, but if entire team is up for it, I am willing to adopt _ as well.

Agreed

**Comment by miyconst** [comment]
>Agreed

@ubbeK are you "agreed" to adopt the `_` or you agree with my opinion regarding the `_`?

**Comment by ubbeK** [comment]
I agree on you opinion and am willing to adopt it if the entire team wants it.

**Comment by threezool** [comment]
I'm with @miyconst in that i prefer to not have the underscore.

**Comment by un-tone** [comment]
As I see the "corefx" and "aspnet" guidelines do not tell to use `_camelCase` for properties, only for fields.
So I propose to continue using `PascalCasing` for all properties including "private" in the manner of the methods naming, since properties is closer to methods, not to fields.

I agree with @miyconst that underscore is not good for naming since it is unreadable and unnecessary if we using `this.`.

**Comment by warpech** [comment]
Based on your input I decide not to add anything regarding `_`.

I added a new point: 

- We use properties rather than fields.

Which goes in line with https://github.com/Starcounter/RebelsLounge/issues/43

Thanks everyone!

**Comment by warpech** [comment]
Added clarification in https://github.com/Starcounter/Guidelines/commit/7c23d0c8d440e7bbfe10b2762120b7167bc53689

**Comment by warpech** [comment]
@rogeralsing has brought to my attention that the guideline to write fields in `PascalCase` is very unorthodox. Fields should be in `camelCase`. I can see that you have already proposed that above, but I missed it. I will make a PR.

**Comment by warpech** [comment]
Moved to a new issue: https://github.com/Starcounter/Guidelines/issues/45
