### ISSUE TITLE
RESTful URIs

### ISSUE THREAD

**Issue by warpech** [Starcounter/Guidelines#9]
I would like to adopt guidelines regarding URIs.

The URIs should be:

1. lowercase
2. have the app name as the first segment
3. end in plural (unless justified)
4. use a relevant HTTP method (see the table below)

<table class="table table-striped table-bordered">
						<thead>
							<tr>
								<th>HTTP method</th>
								<th>CRUD</th>
								<th>Entire Collection (e.g. /customers)</th>
								<th>Specific Item (e.g. /customers/{id})</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>POST</td>
								<td>Create</td>
								<td>201 (Created), 'Location' header with link to /customers/{id} containing new ID.</td>
								<td>404 (Not Found), 409 (Conflict) if resource already exists..</td>
							</tr>
							<tr>
								<td>GET</td>
								<td>Read</td>
								<td>200 (OK), list of customers. Use pagination, sorting and filtering to navigate big lists.</td>
								<td>200 (OK), single customer. 404 (Not Found), if ID not found or invalid.</td>
							</tr>
							<tr>
								<td>PUT</td>
								<td>Update/Replace</td>
								<td>404 (Not Found), unless you want to update/replace every resource in the entire collection.</td>
								<td>200 (OK) or 204 (No Content).  404 (Not Found), if ID not found or invalid.</td>
							</tr>
							<tr>
								<td>PATCH</td>
								<td>Update/Modify</td>
								<td>404 (Not Found), unless you want to modify the collection itself.</td>
								<td>200 (OK) or 204 (No Content).  404 (Not Found), if ID not found or invalid.</td>
							</tr>
							<tr>
								<td>DELETE</td>
								<td>Delete</td>
								<td>404 (Not Found), unless you want to delete the whole collection—not often desirable.</td>
								<td>200 (OK).  404 (Not Found), if ID not found or invalid.</td>
							</tr>
						</tbody>
					</table>

Sources:
- http://www.restapitutorial.com/lessons/restfulresourcenaming.html
- http://www.restapitutorial.com/lessons/httpmethods.html

comments welcome cc @miyconst, @Mackiovello, @joozek78, @mmnosek, @aloscha, @ubbeK, @Joltrix, @KmaTTi89, @diliger, @tomalec, @threezool, @Loudness

**Comment by aloscha** [comment]
quite similar - http://www.ibm.com/support/knowledgecenter/SSFPJS_7.5.1/com.ibm.wbpm.bpc.doc/topics/rdev_restapis_httpmethods.html

it's ok from me

**Comment by tomalec** [comment]
LGTM

**Comment by warpech** [comment]
The guidelines were published at https://github.com/Starcounter/Guidelines/blob/master/uris.md

Please reopen if you have any comments

cc @Starcounter/sc-apps
